GEMINI_API_KEY = "AIzaSyBqYIgJ2QiN9oPgyLp-fxN01QbL_Adiwbs"
GSPREAD_SERVICE_ACCOUNT = "your_google_service_account_json"
SHEET_NAME = "TAICC_AI_Readiness"

[gcp_service_account]
type = "service_account"
project_id = "even-gear-471712-k6"
private_key_id = "0188e25511bacd7ef616228d87690338b1169360"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqE4ANYTv664cd
...rest of your key...
-----END PRIVATE KEY-----"""
client_email = "streamlit-service-account@even-gear-471712-k6.iam.gserviceaccount.com"
client_id = "107459882380094237057"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-service-account%40even-gear-471712-k6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
